resources:
  - name: dwpdigital-dataworks-s3-object-tagger
    type: concourse-registry-image-resource
    source:
      repository: dwpdigital/dataworks-s3-object-tagger
    check_every: 5m

  - name: ecr-dwpdigital-dataworks-s3-object-tagger-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-s3-object-tagger"

  - name: ecr-dwpdigital-dataworks-s3-object-tagger
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-s3-object-tagger"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-dataworks-s3-object-tagger-dev
    serial_groups: [dataworks-s3-object-tagger]
    plan:
      - get: dwpdigital-dataworks-s3-object-tagger
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-s3-object-tagger-dev
        params:
          image: "dwpdigital-dataworks-s3-object-tagger/image.tar"
          additional_tags: "dwpdigital-dataworks-s3-object-tagger/tag"
        attempts: 3

  - name: mirror-dwpdigital-dataworks-s3-object-tagger
    serial_groups: [dataworks-s3-object-tagger]
    plan:
      - get: dwpdigital-dataworks-s3-object-tagger
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-s3-object-tagger
        params:
          image: "dwpdigital-dataworks-s3-object-tagger/image.tar"
          additional_tags: "dwpdigital-dataworks-s3-object-tagger/tag"
        attempts: 3
