meta:
  resources:
    - name: ecr-resource
      type: registry-image-resource
      source:
        repository: unset
        aws_region: ((dataworks.aws_region))
        aws_role_arn: arn:aws:iam::((dataworks.aws_management_dev_acc)):role/ci
        aws_access_key_id: ((dataworks-secrets.ci_aws_access_key_id))
        aws_secret_access_key: ((dataworks-secrets.ci_aws_secret_access_key))
  plan:
    terraform-common-config:
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.terraform_repository))
            tag: ((dataworks.terraform_version))
        params:
          TF_INPUT: false
          TF_CLI_ARGS_apply: -lock-timeout=300s
          TF_CLI_ARGS_plan: -lock-timeout=300s
          TF_VAR_costcode: ((dataworks.costcode))
    terraform-bootstrap:
      task: terraform-bootstrap
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ((dataworks.docker_awscli_repository))
            version: ((dataworks.docker_awscli_version))
            tag: ((dataworks.docker_awscli_version))
        params:
          AWS_REGION: ((dataworks.aws_region))
        run:
          path: sh
          args:
            - -exc
            - |
              python bootstrap_terraform.py
              cp terraform.tf ../terraform-bootstrap
          dir: dataworks-s3-object-tagger
        inputs:
          - name: dataworks-s3-object-tagger
        outputs:
          - name: terraform-bootstrap
    terraform-apply:
      task: terraform-apply
      .: (( inject meta.plan.terraform-common-config ))
      config:
        run:
          path: sh
          args:
            - -exc
            - |
              cp ../terraform-bootstrap/terraform.tf .
              terraform workspace show
              terraform init
              terraform plan -out terraform.plan
              terraform apply -auto-approve terraform.plan
          dir: dataworks-s3-object-tagger
        inputs:
          - name: dataworks-s3-object-tagger
          - name: terraform-bootstrap
    terraform-plan:
      task: terraform-plan
      .: (( inject meta.plan.terraform-common-config ))
      config:
        run:
          path: sh
          args:
            - -exc
            - |
              cp ../terraform-bootstrap/terraform.tf .
              terraform workspace show
              terraform init
              terraform plan $DETAILED_EXITCODE
          dir: dataworks-s3-object-tagger
        inputs:
          - name: dataworks-s3-object-tagger
          - name: terraform-bootstrap
      params:
        DETAILED_EXITCODE: -detailed-exitcode
